// tslint:disable
/**
 * SeikaCenter HTTP API
 * SeikaCenter HTTP API
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Avator
 */
export interface Avator {
    /**
     * 
     * @type {number}
     * @memberof Avator
     */
    cid: number;
    /**
     * 
     * @type {string}
     * @memberof Avator
     */
    name: string;
}

export function AvatorFromJSON(json: any): Avator {
    return AvatorFromJSONTyped(json, false);
}

export function AvatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Avator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cid': json['cid'],
        'name': json['name'],
    };
}

export function AvatorToJSON(value?: Avator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cid': value.cid,
        'name': value.name,
    };
}


