// tslint:disable
/**
 * SeikaCenter HTTP API
 * SeikaCenter HTTP API
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Param,
    ParamFromJSON,
    ParamFromJSONTyped,
    ParamToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {{ [key: string]: Param; }}
     * @memberof InlineResponse200
     */
    effect?: { [key: string]: Param; };
    /**
     * 
     * @type {{ [key: string]: Param; }}
     * @memberof InlineResponse200
     */
    emotion?: { [key: string]: Param; };
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'effect': !exists(json, 'effect') ? undefined : mapValues(json['effect'], ParamFromJSON),
        'emotion': !exists(json, 'emotion') ? undefined : mapValues(json['emotion'], ParamFromJSON),
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'effect': value.effect == null ? undefined : mapValues(value.effect, ParamToJSON),
        'emotion': value.emotion == null ? undefined : mapValues(value.emotion, ParamToJSON),
    };
}


